[package]
name = "rust-hooks"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
colored = "3.0.0"
regex = "1.12.2"

[[bin]]
name = "git-find"
path = "src/main.rs"

